spring.data.mongodb.uri=mongodb+srv://nelsoneapachem:8c7PtUXUSpx1eUbn@proyectoavanzada.yziewqo.mongodb.net/alertasuq?retryWrites=true&w=majority
spring.data.mongodb.database=alertasuq
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

jwt.secret=jwt.secret=7x!A%D*G-KaPdSgVkYp3s6v9y$B?E(H+

# Configuración SMTP (ejemplo para Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=diazorli64@gmail.com
spring.mail.password=erls ydrx mtbf hdqo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# Configuración de Cloudinary
cloudinary.cloud_name=dbpr04p6k
cloudinary.api_key=574195763321855
cloudinary.api_secret=bOyy2repndS95O4vRfheuvj2r7Y

